USE [Stock]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- [Stock]
CREATE TABLE [dbo].[Stock](
	[StockNo] [int] NOT NULL,
	[StockName] [nchar](10) NOT NULL,
	[IsListed] [bit] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[IsEnabled] [bit] NOT NULL,
	[UnabledDate] [datetime] NULL
 CONSTRAINT [PK_Stock] PRIMARY KEY CLUSTERED 
(
	[StockNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO